# Generated by Django 4.2.6 on 2023-11-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_source', models.URLField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/files/')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'JAVASCRIPT VIDEOS',
                'verbose_name_plural': 'JAVASCRIPT VIDEOS',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='html_css',
            options={'ordering': ('-created_at',), 'verbose_name': 'HTML AND CSS VIDEOS', 'verbose_name_plural': 'HTML AND CSS VIDEOS'},
        ),
        migrations.AlterField(
            model_name='html_css',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
    ]
