# Generated by Django 4.2.6 on 2023-11-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_js_alter_html_css_options_alter_html_css_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_source', models.URLField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/files/')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PYTHON VIDEOS',
                'verbose_name_plural': 'PYTHON VIDEOS',
                'ordering': ('-created_at',),
            },
        ),
    ]
