# Generated by Django 4.2.6 on 2023-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_htmlcomment_created_by_pycomment_jscomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djcomment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='htmlcomment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jscomment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pycomment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
    ]
