# Generated by Django 4.2.6 on 2023-12-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_djcomment_comment_alter_htmlcomment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='htmlcomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='htmlcomment',
            name='html_css',
        ),
        migrations.RemoveField(
            model_name='jscomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jscomment',
            name='js',
        ),
        migrations.RemoveField(
            model_name='pycomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pycomment',
            name='py',
        ),
        migrations.DeleteModel(
            name='DJComment',
        ),
        migrations.DeleteModel(
            name='HTMLComment',
        ),
        migrations.DeleteModel(
            name='JSComment',
        ),
        migrations.DeleteModel(
            name='PYComment',
        ),
    ]
